
spring:
  application:
    name: AskItEntityService
  security:
    user :
      name : Raja
      password : Raja@123



  datasource:
    url: jdbc:mysql://localhost:3306/AskItDataBase
    username: root
    password: Rrs@mysql7661

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        enable_lazy_load_no_trans: true


jwt:
  secretKey : "secretKey@AskItRajasecretKey@AskItRajasecretKey@AskItRajasecretKey@AskItRajasecretKey@AskItRajasecretKey@AskItRaja"
  expiry: 3600
